### ISSUE TITLE
Bump Ruby 3.4.1

### ISSUE THREAD

**Issue by guillaumewrobel** [whitequark/parser#1056]
> warning: parser/current is loading parser/ruby34, which recognizes 3.4.0-compliant syntax, but you are running 3.4.1.

**Comment by iliabylich** [comment]
Yes, that's expected, see https://github.com/whitequark/parser/issues/1046.

**Comment by guillaumewrobel** [comment]
Thanks for the PR @iliabylich and kudos for the great work 🙏

**Comment by iliabylich** [comment]
https://github.com/whitequark/parser/pull/1057 has been reverted, I've merged it by accident. Like the linked issue above says I'm not backporting changed anymore (and I can always recommend you to switch to `prism`), so it's unclear if 3.4.x release of `parser` is going to ever happen.

**Comment by guillaumewrobel** [comment]
I see. Though, it's annoying that all Rubocop users will see the deprecation warning 

> warning: parser/current is loading parser/ruby34, which recognizes 3.4.0-compliant syntax, but you are running 3.4.1.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

for each boot.

**Comment by Earlopain** [comment]
RuboCop only ever loads a specific parser version, that doesn't emit such a warning (`parser/33` vs `parser/current`). Without knowing more specifics, I'd say one of your extensions is the cause.

For example, I fixed the same warning in `rubocop-erb` which used `Parser::CurrentRuby` directly to process erb code snippets instead of using `ProcessedSource` from RuboCop.

**Comment by iliabylich** [comment]
There should be a warning for `3.4.0` as well (because even 3.4.0 changes haven't been fully backported), but somehow when we branched out `ruby34.y` we didn't set version in `parser/current.rb` to `3.4.0-dev`. I would say it's a bug that will cause some confusion but there's nothing critical. People would use 3.3 parser otherwise which is basically identical to current 3.4, they would only have a different warning message so again, not a big issue in terms of runtime behavior.

**Comment by Earlopain** [comment]
Yes, I agree it's ok the way it is now, considering the state of the project. Only some fringe syntax changes and nothing where I think the average user would notice. It's more along the lines of those known incompatibilities in the readme.

Basically no one will run 3.4.0 since 3.4.1 was released almost immediately after so that small mistake is even smaller because of that.

**Comment by navidemad** [comment]
We are in ruby 3.4.1 and we are seeing the warnings too

**Comment by navidemad** [comment]
I had the warning due to i18n-tasks gem also, @artemave i made a PR to suppress the warning meanwhile:
https://github.com/glebm/i18n-tasks/pull/613

**Comment by navidemad** [comment]
I am wondering if the easiest fix will be:

```ruby
when /^3\.4\./
    current_version = '3.4.0'
    current_version = '3.4.1' <<<
    if RUBY_VERSION != current_version
      warn_syntax_deviation 'parser/ruby34', current_version
    end
```

Because between ruby 3.4.0 and 3.4.1 there was only few hours apart and it will avoid many warnings :)

**Comment by Earlopain** [comment]
The parser gem is not able to correctly parse any 3.4 version, and likely never will. https://github.com/whitequark/parser/issues/1046

The fact that there is a warning is correct even though it's message is not entirely accurate. It recognizes 3.3 syntax.

**Comment by simi** [comment]
> @Earlopain Yes, I agree it's ok the way it is now, considering the state of the project. Only some fringe syntax changes and nothing where I think the average user would notice. It's more along the lines of those known incompatibilities in the readme.

I don't agree it is ok the way it is now. Per my understanding it should say "parser doesn't support Ruby 3.4", not "it is using wrong 3.4.x version".

**Comment by iliabylich** [comment]
@koic @Earlopain Will rubocop break if we change `3.4.0` version in `parser/current.rb` to `3.4.0-dev`? Rubocop's test suite passes for me locally (we have a `./ci/run_rubocop_specs` script to quickly test it) but I'd like to double-check it with you.

**Comment by Earlopain** [comment]
That should be totally fine. It doesn't use `parser/current`, and the warning would already be emitted anyways since 3.4.0 was basically skipped by Ruby.

**Comment by iliabylich** [comment]
Thanks, then I'll fix it in the next release

**Comment by koic** [comment]
@iliabylich 

> we have a `./ci/run_rubocop_specs` script to quickly test it

It appears that this has already been confirmed. I have confirmed it has passed. Thank you for taking care of this.

**Comment by iliabylich** [comment]
I've released `v3.3.7.1`. Now it shows the warning even for `3.4.0` (as expected).

**Comment by simi** [comment]
@iliabylich I'm still not sure the warning explains properly current situation.

```
irb(main):001> require 'parser/current'
warning: parser/current is loading parser/ruby34, which recognizes 3.4.0-dev-compliant syntax, but you are running 3.4.0.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> true
```

Would it make sense to change warning and make it clear parser doesn't support 3.4 at all. Or at least update the readme compatibility section?

**Comment by iliabylich** [comment]
Labeling a grammar with `-dev` suffix is what we did before with incomplete versions of the grammar that are in development.

What would you like to be in this warning? Feel free to send a PR.

**Comment by simi** [comment]
> Labeling a grammar with `-dev` suffix is what we did before with incomplete versions of the grammar that are in development.
> 
> What would you like to be in this warning? Feel free to send a PR.

Is the current situation different to previous ones, since there is no plan to support 3.4 and newer and prism is recommended? At least, that's my understanding reading issues around this repo.
